name: Manual build Stan models

on:
  workflow_dispatch: {}

env:
  CMDSTAN_VERSION: "2.36.0"   # keep in sync with setup.py

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip + install build deps
        run: python -m pip install -U pip setuptools wheel "cmdstanpy==1.2.*"

      # Optional: cache a home-dir CmdStan to speed things up in future manual runs.
      # NOTE: Your setup.py installs CmdStan inside the build dir, not ~/.cmdstan,
      # so this cache WON'T be used unless you later change setup.py to use ~/.cmdstan.
      - name: Cache ~/.cmdstan (optional)
        uses: actions/cache@v4
        with:
          path: ~/.cmdstan
          key: ${{ runner.os }}-cmdstan-${{ env.CMDSTAN_VERSION }}

      - name: Build wheel via setup.py (repackage cmdstan)
        env:
          GLORIA_REPACKAGE_CMDSTAN: "TRUE"
        run: |
          python setup.py bdist_wheel
          python -c "import pathlib; p=list(pathlib.Path('dist').glob('*.whl')); print('Built wheel:', p[0] if p else 'none')"

      - name: Collect build tree for inspection
        shell: bash
        run: |
          mkdir -p artifact_tree
          # wheel(s)
          cp -v dist/*.whl artifact_tree/ || true
          # copy the built package area where setup.py staged executables
          # (build/lib/... mirrors the installed package layout)
          if [ -d "build/lib" ]; then
            echo "Listing build/lib contents:"
            find build/lib -maxdepth 4 -type f | sort
            # zip relevant dirs for inspection
            python - <<'PY'
import shutil, pathlib
root = pathlib.Path("build/lib")
out = pathlib.Path("artifact_tree/build_lib.zip")
shutil.make_archive(str(out.with_suffix('')), 'zip', str(root))
print("Zipped", out)
PY
          fi

      - name: Upload artifacts (wheel + build tree zip)
        uses: actions/upload-artifact@v4
        with:
          name: stan-build-${{ matrix.os }}
          path: |
            artifact_tree/*.whl
            artifact_tree/*.zip
